name: style-transfer

channels:
    - pytorch
    - nvidia
    - anaconda
    - conda-forge

dependencies:
    - python=3.9
    - pytorch-cuda=11.7
    - pytorch=2.0
    - torchvision
    - tqdm
    - Pillow
